import { Epilogue } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/side-bar";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <main className="flex h-full">
          <aside>
            <SideBar />
          </aside>
          <section className="flex flex-col flex-1">{children}</section>
        </main>
      </body>
    </html>
  );
}
